### ISSUE TITLE
request timeout when running pandoc-manubot-cite

### ISSUE THREAD

**Issue by phildong** [manubot/manubot#309] opened 2022-01-07 17:14 UTC
Hey first of all thanks for the great tool!
I have been happy with manubot until recently I'm getting a "502 bad gateway" issue for all of my citations.
Here is an example message:
```
## ERROR
Error fetching metadata for doi:10.1007/978-3-319-67558-9_33.
Invalid response from https://data.crosscite.org/10.1007/978-3-319-67558-9_33:
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
```

I'm not sure this is the correct place to report since it looks like a temporary crosscite.org website issue.
However I have been trying for a few days now and I can never successfully finish a build.
I'm wondering given the instability of crosscite.org what's the best way to get around this problem and get the manuscript properly built?
I do have a local cached `reference.json` generated by manubot automatically, I'm wondering if there's an easy way to tell manubot to just use that (without manually changing all my citation keys of course)
Thanks in advance for your help!

**Comment by dhimmel** [comment] 2022-01-07 17:29
We also got a similar error for a catalog [build](https://github.com/manubot/catalog/runs/4698320469?check_suite_focus=true#step:5:221):

```
ERROR: Error fetching metadata for doi:10.1101/474403.
Invalid response from https://data.crosscite.org/10.1101/474403:
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>
```

Slightly different error code (502 versus 503). 

The 502 might be the same issue as https://github.com/crosscite/content-negotiation/issues/104.

I'll follow up with some fixes Manubot can implement, but in the meantime you can provide the metadata manually. Are you using Manubot to write a manuscript? If so, use [these instructions](https://github.com/manubot/rootstock/blob/c4a394e4293751fdca07f17bb731a54ebdfdb50c/USAGE.md#reference-metadata).

**Comment by dhimmel** [comment] 2022-01-07 17:37
We should consider reverting part of e9128567387d7e7eaa7b0a7765d8f06ca2238dc5 to switch the default for `content_negotiation_url` to `https://doi.org` from `https://data.crosscite.org`.


```sh
# this works
curl --silent --location \
  --header "Accept: application/vnd.citationstyles.csl+json" \
  https://doi.org/10.1007/978-3-319-67558-9_33

# this fails
curl --silent --location \
  --header "Accept: application/vnd.citationstyles.csl+json" \
  https://data.crosscite.org/10.1007/978-3-319-67558-9_33
```

**Comment by phildong** [comment] 2022-01-07 17:40
Thanks for the quick response!
Just to make sure -- currently the workaround would be to manually copy-paste the info from generated `reference.json` to `manual-references.json` and manually change all the `id`s? (cause in the auto-generated file the `id` are short hashes instead of original doi keys)
Is there any better way for doing this?

**Comment by dhimmel** [comment] 2022-01-07 17:46
You'll just need to copy the single reference that is failing into `manual-references.json`, although you can copy all if you'd like cached references for faster builds and to prevent future errors. You can keep the short citation keys as is (`id` field). The longer form will be detected in the `note` field.

**Comment by phildong** [comment] 2022-01-07 17:58
I can confirm copy-pasting everything from `reference.json` to `manual-references.json` works like a charm (all my citations were failing before), and no manual change of id was needed. @dhimmel Thank you so much for the help!

**Comment by dhimmel** [comment] 2022-01-07 18:39
Incidentally, the following is now working `manubot cite 10.1007/978-3-319-67558-9_33 10.1101/474403`. Seems like the upstream DataCite content negotiation errors have been fixed.

I also created https://github.com/manubot/manubot/pull/310, which will help with future errors in DataCite content negotiation by falling back to CrossCite content negotiation.

**Comment by dhimmel** [comment] 2022-01-08 23:34
Released [manubot 0.5.2](https://github.com/manubot/manubot/releases/tag/v0.5.2) which includes the fallback DOI Content Negotiation provider.

Also upgraded rootstock in https://github.com/manubot/rootstock/commit/989fa3d1d0a36dd13f8c34ef7615f424766bc4fc.

@phildong [upgrading](https://github.com/manubot/rootstock/blob/989fa3d1d0a36dd13f8c34ef7615f424766bc4fc/SETUP.md#merging-upstream-rootstock-changes) your manuscript to use the latest rootstock will help prevent additional errors like this.

If everything looks good, you can close this issue.

**Comment by aseedb** [comment] 2022-01-12 13:30
Hi, I am getting the same issues for my manuscript. I have upgraded the manuscript to following the procedure you mentioned above. Unfortunately the problem is not solved. Do I need to upgrade anything else? Note that the manuscript is private but @dhimmel I can add you to the project if you need to have a look into it.

One error that sounds weird is this one:
```
## ERROR
Generating csl_item for 'doi' failed due to a NotImplementedError:
Manubot does not know how to generate a csl_item for 'doi'
```
maybe a spelling mistake in my manuscript.

Apart from that I am getting lots of errors such as
```
## ERROR
Error fetching metadata for doi:10.1002/embr.201337807.
Invalid response from https://data.crosscite.org/10.1002/embr.201337807:
<h2>This website is under heavy load (queue full)</h2><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>
## WARNING
Error in get_doi_csl_item_datacite for 10.1002/embr.201337807 due to a JSONDecodeError:
Expecting value: line 1 column 1 (char 0)
```
and like that as well:
```
## ERROR
Error fetching metadata for doi:10.1006/jsbi.1996.0013.
Invalid response from https://data.crosscite.org/10.1006/jsbi.1996.0013:
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

## WARNING
Error in get_doi_csl_item_datacite for 10.1006/jsbi.1996.0013 due to a JSONDecodeError:
Expecting value: line 1 column 1 (char 0)
```

**Comment by dhimmel** [comment] 2022-01-12 14:58
> Manubot does not know how to generate a csl_item for 'doi'

You probably have a malformated citation like `doi 10.1006/jsbi.1996.0013` (notice space) or `doi;10.1006/jsbi.1996.0013`.

> Apart from that I am getting lots of errors such as

Even with the latest changes, these errors might show up in the logs. We're still querying the datacite endpoint, but just have an additional backup when it fails. Let's see if your CI passes once you fix the first error.

**Comment by aseedb** [comment] 2022-01-13 10:36
Oh yes, the issue was `doi: `

Yes the errors show up in the logs but the CI actually passed 👍 
Thank you for your quick support!

**Comment by aseedb** [comment] 2022-01-17 08:19
I would like to suggest a change of behaviour. My manuscript builds in 7 to 8 minutes when data.crosscite.org correctly works. But when it makes errors, the manuscript builds in 18 to 29 minutes. I guess that this is due to the CI interrogating crosscite.org and waiting for request timeout for every reference. I would suggest switching to the alternative reference database for all references once crosscite gives an error.

**Comment by agitter** [comment] 2022-01-17 15:07
That behavior would make sense when data.crosscite.org is having systematic issues.  However, in the past we often saw that a single reference would fail with data.crosscite.org and 100s of others would succeed.  In that case, we don't necessarily want one failure to trigger a change in the primary data source.

This is something to monitor if we encountering increasing data.crosscite.org failures or learn it isn't being maintained.

**Comment by dhimmel** [comment] 2022-01-19 15:06
We heard back from DataCite at https://github.com/crosscite/content-negotiation/issues/104#issuecomment-1015311377:

> we have been experiencing some issues with the stability of the Content Negotiation service recently due to abnormally high load. This is under active investigation and we hope to have remediation in place as soon as possible. There is an open StatusPage incident here: https://status.datacite.org/incidents/k7rjjq59kpyb

From that page on Jan 11, 2022 - 11:00 UTC:

> During the past week or so we've noticed a huge surge of increased traffic to the Content Negotiation Service. This has unfortunately caused various problems with requests not being resolved. This is currently affecting both the Content Negotiation service but also the Citation Formatter service.
> 
> We've made some initial improvements to support the increased load on the service, but it is unfortunately still causing issues.
> We will continue to investigate.

So hoping the outage gets resolved soon. There's two Manubot changes that come to mind:

1. add a DOI method that uses the DOI URL and then scrapes metadata from the publisher page with Zotero translation-server.
2. cache references more aggressively. We do use requests-cache, but it's clear that it's not caching all references. We can also get reference metadata from the output branch and reuse it for future builds.

**Comment by dhimmel** [comment] 2022-02-12 14:39
Noting that DataCite has removed Content Negotiation support permanently for Crossref DOI, see https://github.com/crosscite/content-negotiation/issues/104#issuecomment-1034147358. 

> add a DOI method that uses the DOI URL and then scrapes metadata from the publisher page with Zotero translation-server.

This was done in https://github.com/manubot/manubot/pull/319.

**Closed by dhimmel** 2022-02-12 14:39 UTC
