### ISSUE TITLE
bioRxiv CSL metadata does not set container-title

### ISSUE THREAD

**Issue by agitter** [manubot/manubot#16] opened 2017-10-19 11:18 UTC
As I noted in greenelab/meta-review#18, bioRxiv references show _Cold Spring Harbor Laboratory_ instead of _bioRxiv_ in the reference list.  This is because the JSON file from CrossRef has `"container-title":[]`.

I presume bioRxiv supplies the citation information for the DOI.  Would it be worthwhile to contact them to see if we can correct the references by fixing the upstream data?

**Comment by dhimmel** [comment] 2017-10-19 16:42
Yep you can see the metadata returned for https://doi.org/10.1101/142760 in [this file](https://github.com/greenelab/meta-review/blob/304f1f8193e2780c3cda630786d68cc830bbe7a7/references.json#L1467-L1752). Despite depositing detailed Crossref metadata for many fields, bioRxiv never sets `container-title`. In fact, `bioRxiv` doesn't appear anywhere in the metadata. I do think `container-title` should be set to `bioRxiv`.

> Would it be worthwhile to contact them to see if we can correct the references by fixing the upstream data?

Yeah, the problem is they have no public issue tracker (like a GitHub Issues) that I'm aware of. Therefore, I usually report issues via Twitter by tagging `@biorxivpreprint @cshperspectives`. Reporting issues by Twitter is obviously not very effective, but I am not aware of a better way.

@agitter do you want to tweet them a link to this issue?

**Comment by dhimmel** [comment] 2017-10-19 16:48
FYI definitions for CSL JSON items [are here](http://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables). Relevant ones for this issue are:

> container-title: title of the container holding the item (e.g. the book title for a book chapter, the journal title for a journal article)
> publisher

Some of the issue could be with how Crossref converts metadata submitted to them to CSL JSON via DOI Content Negotiation. Tagging @gbilder in case he knows why bioRxiv doesn't show up under `container-title`.

**Comment by agitter** [comment] 2017-10-19 19:08
I needed more than 140 characters so I wrote to biorxiv.feedback@cshl.edu, which I found on the bioRxiv About page.  I'll follow up by tweet if I don't hear back.

**Comment by agitter** [comment] 2018-01-09 13:06
I followed up [on Twitter](https://twitter.com/anthonygitter/status/950715134544138240).

**Comment by dhimmel** [comment] 2018-02-17 02:17
This is also an issue with PeerJ Preprints (at least since they recently switched to Crossref from DataCite for registering DOIs). `container-title` is not set ([see tweet](https://twitter.com/dhimmel/status/964683677732044800)). Therefore, we fallback to publisher which is `PeerJ` making citations appear to be to the journal not preprint server.

**Comment by agitter** [comment] 2019-02-06 15:18
@dhimmel's Zotero discussion in https://github.com/greenelab/manubot-rootstock/issues/176 reminded me that we can use the Zotero translation server to process any URL, even those for a manuscript with a DOI.  One workaround for the `container-title` of bioRxiv preprints would be to cite them by URL.

Compare `manubot cite url:https://doi.org/gftzwz` (output below) to the DOI citation of the same manuscript in https://github.com/greenelab/manubot-rootstock/issues/176#issuecomment-461053995.

<details>

```json
[
  {
    "type": "article-journal",
    "title": "Tracking the popularity and outcomes of all bioRxiv preprints",
    "container-title": "bioRxiv",
    "page": "515643",
    "source": "www.biorxiv.org",
    "abstract": "<p>Researchers in the life sciences are posting their work to preprint servers at an unprecedented and increasing rate, sharing papers online before (or instead of) publication in peer-reviewed journals. Though the popularity and practical benefits of preprints are driving policy changes at journals and funding organizations, there is little bibliometric data available to measure trends in their usage. Here, we collected and analyzed data on all 37,648 preprints that were uploaded to bioRxiv.org, the largest biology-focused preprint server, in its first five years. We find that preprints on bioRxiv are being read more than ever before (1.1 million downloads in October 2018 alone) and that the rate of preprints being posted has increased to a recent high of more than 2,100 per month. We also find that two-thirds of bioRxiv preprints posted in 2016 or earlier were later published in peer-reviewed journals, and that the majority of published preprints appeared in a journal less than six months after being posted. We evaluate which journals have published the most preprints, and find that preprints with more downloads are likely to be published in journals with a higher impact factor. Lastly, we developed Rxivist.org, a website for downloading and interacting programmatically with indexed metadata on bioRxiv preprints.</p>",
    "URL": "https://www.biorxiv.org/content/10.1101/515643v1",
    "DOI": "10.1101/515643",
    "language": "en",
    "author": [
      {
        "family": "Blekhman",
        "given": "Ran"
      },
      {
        "family": "Abdill",
        "given": "Richard J."
      }
    ],
    "issued": {
      "date-parts": [
        [
          "2019",
          1,
          13
        ]
      ]
    },
    "accessed": {
      "date-parts": [
        [
          "2019",
          2,
          6
        ]
      ]
    },
    "id": "lewKb9A8"
  }
]
```
</details>

**Comment by dhimmel** [comment] 2019-02-06 16:33
In the source HTML of https://www.biorxiv.org/content/10.1101/515643v1, the following values are set

```html
<meta name="og:site_name" property="og:site_name" content="bioRxiv" />
<meta name="citation_journal_title" content="bioRxiv" />
<meta name="DC.Publisher" content="Cold Spring Harbor Laboratory" />
<meta name="citation_publisher" content="Cold Spring Harbor Laboratory" />
```

So I think it is absolutely an omission that bioRxiv does not submit `container-title` metadata to Crossref.

`manubot cite url:https://doi.org/gftzwz` or `manubot cite url:https://www.biorxiv.org/content/10.1101/515643v1` is a good temporary workaround. Note that translation-server's behavior may change in the future to rely more on the DOI metadata, which could cause the missing `container-title` to return.

**Comment by agitter** [comment] 2020-06-12 13:14
It looks like this issue has been resolved
```
$ manubot cite --render doi:10.1101/515643
1. Tracking the popularity and outcomes of all bioRxiv preprints
Richard J. Abdill, Ran Blekhman
bioRxiv (2019-04-02) https://doi.org/gftzwz
DOI: 10.1101/515643
```

Without the `--render` option, the JSON includes `"container-title": "bioRxiv",`.

@dhimmel can you please close this issue if you agree?

**Comment by dhimmel** [comment] 2020-06-12 13:29
I don't see this fixed in the Crossref metadata at https://api.crossref.org/works/10.1101/515643/transform/application/vnd.crossref.unixsd+xml:

```xml
<crm-item name="publisher-name" type="string">Cold Spring Harbor Laboratory</crm-item>
<crm-item name="prefix-name" type="string">Cold Spring Harbor Laboratory</crm-item>
```

Or at https://search.crossref.org/?q=10.1101%2F515643

> ![image](https://user-images.githubusercontent.com/1117703/84507036-39023180-ac8e-11ea-9fec-113dcdf153d8.png)

But the datacite infrastructure seems to handle it if I understand [this test](https://github.com/datacite/bolognese/blob/027d2dac5b0a30136d82c87ff8b3fc970f093916/spec/readers/crossref_reader_spec.rb#L174):

```ruby
      expect(subject.publisher).to eq("bioRxiv")
```

`container-title` is set to `bioRxiv` at https://data.crosscite.org/application/vnd.citationstyles.csl+json/10.1101/515643.

@mfenner, this is great! Do you know where the metadata for bioRxiv preprints is getting fixed to include `container-title`?

**Closed** 2020-06-12 13:40 UTC
